/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the homepage.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Short paragraph displayed on the left side of the hero.
             */
            mainText: string;
            readMoreLabel?: string | null;
            readMoreHref?: string | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            /**
             * First line of the large overlay text.
             */
            overlayPart1: string;
            /**
             * Second line of the large overlay text.
             */
            overlayPart2: string;
            /**
             * Hex color for the circle behind the image (e.g. #facc15 for yellow).
             */
            circleColor?: string | null;
            /**
             * Small text shown at the bottom right of the hero.
             */
            locationText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Optional heading above the logo strip.
             */
            heading?: string | null;
            logos?:
              | {
                  name: string;
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Duration in seconds for one full scroll cycle. Lower = faster.
             */
            speed?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'companies';
          }
        | {
            heading: string;
            description?: string | null;
            testimonials?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  /**
                   * Featured testimonials span two columns and two rows.
                   */
                  featured?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  /**
                   * Displayed on the opposite side (e.g. "2020 – 2023", "Chapter 1").
                   */
                  label: string;
                  title: string;
                  text?: string | null;
                  image?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutMe';
          }
        | {
            /**
             * Logos displayed in a grid on the left side. Ideally 4 or 8 logos.
             */
            logos?:
              | {
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  alt: string;
                  /**
                   * Show the logo in its original colors instead of grayscale/inverted.
                   */
                  disableFilter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            overlayPart1: string;
            overlayPart2: string;
            circleColor?: string | null;
            locationText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV2';
          }
        | {
            heading?: string | null;
            description?: string | null;
            /**
             * CSS color for the animated connection lines (e.g. #0ea5e9)
             */
            lineColor?: string | null;
            /**
             * CSS color for the continent dots (8-char hex for alpha, e.g. #FFFF7F40)
             */
            dotColor?: string | null;
            showLabels?: boolean | null;
            loop?: boolean | null;
            /**
             * Each connection draws an animated arc between two points on the map.
             */
            connections?:
              | {
                  /**
                   * Select a European capital or US state capital
                   */
                  startCity:
                    | '_europe_header'
                    | 'amsterdam'
                    | 'andorra-la-vella'
                    | 'athens'
                    | 'belgrade'
                    | 'berlin'
                    | 'bern'
                    | 'bratislava'
                    | 'brussels'
                    | 'bucharest'
                    | 'budapest'
                    | 'chisinau'
                    | 'copenhagen'
                    | 'dublin'
                    | 'helsinki'
                    | 'kyiv'
                    | 'ljubljana'
                    | 'london'
                    | 'luxembourg'
                    | 'madrid'
                    | 'minsk'
                    | 'monaco'
                    | 'moscow'
                    | 'nicosia'
                    | 'oslo'
                    | 'paris'
                    | 'podgorica'
                    | 'prague'
                    | 'pristina'
                    | 'reykjavik'
                    | 'riga'
                    | 'rome'
                    | 'sarajevo'
                    | 'skopje'
                    | 'sofia'
                    | 'stockholm'
                    | 'tallinn'
                    | 'tirana'
                    | 'vaduz'
                    | 'valletta'
                    | 'vienna'
                    | 'vilnius'
                    | 'warsaw'
                    | 'zagreb'
                    | '_usa_header'
                    | 'albany'
                    | 'annapolis'
                    | 'atlanta'
                    | 'augusta'
                    | 'austin'
                    | 'baton-rouge'
                    | 'bismarck'
                    | 'boise'
                    | 'boston'
                    | 'carson-city'
                    | 'charleston'
                    | 'cheyenne'
                    | 'columbia'
                    | 'columbus'
                    | 'concord'
                    | 'denver'
                    | 'des-moines'
                    | 'dover'
                    | 'frankfort'
                    | 'harrisburg'
                    | 'hartford'
                    | 'helena'
                    | 'honolulu'
                    | 'indianapolis'
                    | 'jackson'
                    | 'jefferson-city'
                    | 'juneau'
                    | 'lansing'
                    | 'lincoln'
                    | 'little-rock'
                    | 'madison'
                    | 'montgomery'
                    | 'montpelier'
                    | 'nashville'
                    | 'oklahoma-city'
                    | 'olympia'
                    | 'phoenix'
                    | 'pierre'
                    | 'providence'
                    | 'raleigh'
                    | 'richmond'
                    | 'sacramento'
                    | 'saint-paul'
                    | 'salem'
                    | 'salt-lake-city'
                    | 'santa-fe'
                    | 'springfield-il'
                    | 'tallahassee'
                    | 'topeka'
                    | 'trenton'
                    | 'washington-dc';
                  /**
                   * Select a European capital or US state capital
                   */
                  endCity:
                    | '_europe_header'
                    | 'amsterdam'
                    | 'andorra-la-vella'
                    | 'athens'
                    | 'belgrade'
                    | 'berlin'
                    | 'bern'
                    | 'bratislava'
                    | 'brussels'
                    | 'bucharest'
                    | 'budapest'
                    | 'chisinau'
                    | 'copenhagen'
                    | 'dublin'
                    | 'helsinki'
                    | 'kyiv'
                    | 'ljubljana'
                    | 'london'
                    | 'luxembourg'
                    | 'madrid'
                    | 'minsk'
                    | 'monaco'
                    | 'moscow'
                    | 'nicosia'
                    | 'oslo'
                    | 'paris'
                    | 'podgorica'
                    | 'prague'
                    | 'pristina'
                    | 'reykjavik'
                    | 'riga'
                    | 'rome'
                    | 'sarajevo'
                    | 'skopje'
                    | 'sofia'
                    | 'stockholm'
                    | 'tallinn'
                    | 'tirana'
                    | 'vaduz'
                    | 'valletta'
                    | 'vienna'
                    | 'vilnius'
                    | 'warsaw'
                    | 'zagreb'
                    | '_usa_header'
                    | 'albany'
                    | 'annapolis'
                    | 'atlanta'
                    | 'augusta'
                    | 'austin'
                    | 'baton-rouge'
                    | 'bismarck'
                    | 'boise'
                    | 'boston'
                    | 'carson-city'
                    | 'charleston'
                    | 'cheyenne'
                    | 'columbia'
                    | 'columbus'
                    | 'concord'
                    | 'denver'
                    | 'des-moines'
                    | 'dover'
                    | 'frankfort'
                    | 'harrisburg'
                    | 'hartford'
                    | 'helena'
                    | 'honolulu'
                    | 'indianapolis'
                    | 'jackson'
                    | 'jefferson-city'
                    | 'juneau'
                    | 'lansing'
                    | 'lincoln'
                    | 'little-rock'
                    | 'madison'
                    | 'montgomery'
                    | 'montpelier'
                    | 'nashville'
                    | 'oklahoma-city'
                    | 'olympia'
                    | 'phoenix'
                    | 'pierre'
                    | 'providence'
                    | 'raleigh'
                    | 'richmond'
                    | 'sacramento'
                    | 'saint-paul'
                    | 'salem'
                    | 'salt-lake-city'
                    | 'santa-fe'
                    | 'springfield-il'
                    | 'tallahassee'
                    | 'topeka'
                    | 'trenton'
                    | 'washington-dc';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'worldMap';
          }
      )[]
    | null;
  meta?: {
    /**
     * Overrides the default site title.
     */
    title?: string | null;
    /**
     * Overrides the default site description.
     */
    description?: string | null;
    ogImage?: {
      source?: ('upload' | 'url') | null;
      upload?: (number | null) | Media;
      /**
       * Full URL to an image (JPG, PNG, WebP, SVG)
       */
      url?: string | null;
    };
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              mainText?: T;
              readMoreLabel?: T;
              readMoreHref?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              overlayPart1?: T;
              overlayPart2?: T;
              circleColor?: T;
              locationText?: T;
              id?: T;
              blockName?: T;
            };
        companies?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    name?: T;
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              speed?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              description?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutMe?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    title?: T;
                    text?: T;
                    image?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroV2?:
          | T
          | {
              logos?:
                | T
                | {
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    alt?: T;
                    disableFilter?: T;
                    id?: T;
                  };
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              overlayPart1?: T;
              overlayPart2?: T;
              circleColor?: T;
              locationText?: T;
              id?: T;
              blockName?: T;
            };
        worldMap?:
          | T
          | {
              heading?: T;
              description?: T;
              lineColor?: T;
              dotColor?: T;
              showLabels?: T;
              loop?: T;
              connections?:
                | T
                | {
                    startCity?: T;
                    endCity?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?:
          | T
          | {
              source?: T;
              upload?: T;
              url?: T;
            };
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used as fallback in <title> tags.
   */
  siteName?: string | null;
  /**
   * Used when a page has no individual meta description.
   */
  siteDescription?: string | null;
  defaultOgImage?: {
    source?: ('upload' | 'url') | null;
    upload?: (number | null) | Media;
    /**
     * Full URL to an image (JPG, PNG, WebP, SVG)
     */
    url?: string | null;
  };
  /**
   * URL to a .ico, .png, or .svg favicon.
   */
  faviconUrl?: string | null;
  /**
   * e.g. G-XXXXXXXXXX
   */
  googleAnalyticsId?: string | null;
  /**
   * Hex color code used as the brand primary color.
   */
  primaryColor?: string | null;
  twitterHandle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Paste a URL to your logo image (PNG, SVG, WebP). Leave blank to use the default icon.
   */
  logoUrl?: string | null;
  logoAlt?: string | null;
  /**
   * Height of the logo in pixels (16–80px). Width scales automatically.
   */
  logoHeight?: number | null;
  navItems?:
    | {
        label: string;
        href: string;
        dropdownItems?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logoText?: string | null;
  description?: string | null;
  /**
   * Leave blank to auto-generate with current year.
   */
  copyrightText?: string | null;
  githubUrl?: string | null;
  linkedinUrl?: string | null;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  youtubeUrl?: string | null;
  /**
   * Leave empty to use default links.
   */
  linkGroups?:
    | {
        label: string;
        links?:
          | {
              title: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultOgImage?:
    | T
    | {
        source?: T;
        upload?: T;
        url?: T;
      };
  faviconUrl?: T;
  googleAnalyticsId?: T;
  primaryColor?: T;
  twitterHandle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoUrl?: T;
  logoAlt?: T;
  logoHeight?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoText?: T;
  description?: T;
  copyrightText?: T;
  githubUrl?: T;
  linkedinUrl?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  youtubeUrl?: T;
  linkGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              title?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}