/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  optimizeFormat?: ('auto' | 'webp' | 'avif' | 'jpeg' | 'png') | null;
  optimizeQuality?: number | null;
  optimizeMaxWidth?: number | null;
  optimizeMaxHeight?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the homepage.
   */
  slug: string;
  /**
   * Used for sitemap priority and schema markup.
   */
  pageType?: ('general' | 'pillar' | 'job_role' | 'job_role_location' | 'tool' | 'topic' | 'pillar_support') | null;
  layout?:
    | (
        | {
            /**
             * Short paragraph displayed on the left side of the hero.
             */
            mainText: string;
            readMoreLabel?: string | null;
            readMoreHref?: string | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            /**
             * First line of the large overlay text.
             */
            overlayPart1: string;
            /**
             * Second line of the large overlay text.
             */
            overlayPart2: string;
            /**
             * Hex color for the circle behind the image (e.g. #facc15 for yellow).
             */
            circleColor?: string | null;
            /**
             * Small text shown at the bottom right of the hero.
             */
            locationText?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Optional heading above the logo strip.
             */
            heading?: string | null;
            logos?:
              | {
                  name: string;
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Duration in seconds for one full scroll cycle. Lower = faster.
             */
            speed?: number | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'companies';
          }
        | {
            heading: string;
            description?: string | null;
            testimonials?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  /**
                   * Featured testimonials span two columns and two rows.
                   */
                  featured?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  /**
                   * Displayed on the opposite side (e.g. "2020 – 2023", "Chapter 1").
                   */
                  label: string;
                  title: string;
                  text?: string | null;
                  image?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutMe';
          }
        | {
            /**
             * Logos displayed in a grid on the left side. Ideally 4 or 8 logos.
             */
            logos?:
              | {
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  alt: string;
                  /**
                   * Show the logo in its original colors instead of grayscale/inverted.
                   */
                  disableFilter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            overlayPart1: string;
            overlayPart2: string;
            circleColor?: string | null;
            locationText?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV2';
          }
        | {
            heading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * CSS color for the animated connection lines (e.g. #0ea5e9)
             */
            lineColor?: string | null;
            /**
             * CSS color for the continent dots (8-char hex for alpha, e.g. #FFFF7F40)
             */
            dotColor?: string | null;
            showLabels?: boolean | null;
            loop?: boolean | null;
            /**
             * Each connection draws an animated arc between two points on the map.
             */
            connections?:
              | {
                  /**
                   * Select a European capital or US state capital
                   */
                  startCity:
                    | '_europe_header'
                    | 'amsterdam'
                    | 'andorra-la-vella'
                    | 'athens'
                    | 'belgrade'
                    | 'berlin'
                    | 'bern'
                    | 'bratislava'
                    | 'brussels'
                    | 'bucharest'
                    | 'budapest'
                    | 'chisinau'
                    | 'copenhagen'
                    | 'dublin'
                    | 'helsinki'
                    | 'kyiv'
                    | 'ljubljana'
                    | 'london'
                    | 'luxembourg'
                    | 'madrid'
                    | 'minsk'
                    | 'monaco'
                    | 'moscow'
                    | 'nicosia'
                    | 'oslo'
                    | 'paris'
                    | 'podgorica'
                    | 'prague'
                    | 'pristina'
                    | 'reykjavik'
                    | 'riga'
                    | 'rome'
                    | 'sarajevo'
                    | 'skopje'
                    | 'sofia'
                    | 'stockholm'
                    | 'tallinn'
                    | 'tirana'
                    | 'vaduz'
                    | 'valletta'
                    | 'vienna'
                    | 'vilnius'
                    | 'warsaw'
                    | 'zagreb'
                    | '_usa_header'
                    | 'albany'
                    | 'annapolis'
                    | 'atlanta'
                    | 'augusta'
                    | 'austin'
                    | 'baton-rouge'
                    | 'bismarck'
                    | 'boise'
                    | 'boston'
                    | 'carson-city'
                    | 'charleston'
                    | 'cheyenne'
                    | 'columbia'
                    | 'columbus'
                    | 'concord'
                    | 'denver'
                    | 'des-moines'
                    | 'dover'
                    | 'frankfort'
                    | 'harrisburg'
                    | 'hartford'
                    | 'helena'
                    | 'honolulu'
                    | 'indianapolis'
                    | 'jackson'
                    | 'jefferson-city'
                    | 'juneau'
                    | 'lansing'
                    | 'lincoln'
                    | 'little-rock'
                    | 'madison'
                    | 'montgomery'
                    | 'montpelier'
                    | 'nashville'
                    | 'oklahoma-city'
                    | 'olympia'
                    | 'phoenix'
                    | 'pierre'
                    | 'providence'
                    | 'raleigh'
                    | 'richmond'
                    | 'sacramento'
                    | 'saint-paul'
                    | 'salem'
                    | 'salt-lake-city'
                    | 'santa-fe'
                    | 'springfield-il'
                    | 'tallahassee'
                    | 'topeka'
                    | 'trenton'
                    | 'washington-dc'
                    | '_regions_header'
                    | 'emea'
                    | 'usa'
                    | 'canada'
                    | 'australia'
                    | 'new-zealand';
                  /**
                   * Select a European capital or US state capital
                   */
                  endCity:
                    | '_europe_header'
                    | 'amsterdam'
                    | 'andorra-la-vella'
                    | 'athens'
                    | 'belgrade'
                    | 'berlin'
                    | 'bern'
                    | 'bratislava'
                    | 'brussels'
                    | 'bucharest'
                    | 'budapest'
                    | 'chisinau'
                    | 'copenhagen'
                    | 'dublin'
                    | 'helsinki'
                    | 'kyiv'
                    | 'ljubljana'
                    | 'london'
                    | 'luxembourg'
                    | 'madrid'
                    | 'minsk'
                    | 'monaco'
                    | 'moscow'
                    | 'nicosia'
                    | 'oslo'
                    | 'paris'
                    | 'podgorica'
                    | 'prague'
                    | 'pristina'
                    | 'reykjavik'
                    | 'riga'
                    | 'rome'
                    | 'sarajevo'
                    | 'skopje'
                    | 'sofia'
                    | 'stockholm'
                    | 'tallinn'
                    | 'tirana'
                    | 'vaduz'
                    | 'valletta'
                    | 'vienna'
                    | 'vilnius'
                    | 'warsaw'
                    | 'zagreb'
                    | '_usa_header'
                    | 'albany'
                    | 'annapolis'
                    | 'atlanta'
                    | 'augusta'
                    | 'austin'
                    | 'baton-rouge'
                    | 'bismarck'
                    | 'boise'
                    | 'boston'
                    | 'carson-city'
                    | 'charleston'
                    | 'cheyenne'
                    | 'columbia'
                    | 'columbus'
                    | 'concord'
                    | 'denver'
                    | 'des-moines'
                    | 'dover'
                    | 'frankfort'
                    | 'harrisburg'
                    | 'hartford'
                    | 'helena'
                    | 'honolulu'
                    | 'indianapolis'
                    | 'jackson'
                    | 'jefferson-city'
                    | 'juneau'
                    | 'lansing'
                    | 'lincoln'
                    | 'little-rock'
                    | 'madison'
                    | 'montgomery'
                    | 'montpelier'
                    | 'nashville'
                    | 'oklahoma-city'
                    | 'olympia'
                    | 'phoenix'
                    | 'pierre'
                    | 'providence'
                    | 'raleigh'
                    | 'richmond'
                    | 'sacramento'
                    | 'saint-paul'
                    | 'salem'
                    | 'salt-lake-city'
                    | 'santa-fe'
                    | 'springfield-il'
                    | 'tallahassee'
                    | 'topeka'
                    | 'trenton'
                    | 'washington-dc'
                    | '_regions_header'
                    | 'emea'
                    | 'usa'
                    | 'canada'
                    | 'australia'
                    | 'new-zealand';
                  id?: string | null;
                }[]
              | null;
            /**
             * Up to 3 big numbers displayed below the map.
             */
            stats?:
              | {
                  /**
                   * e.g. "10+", "50K", "99%"
                   */
                  value: string;
                  /**
                   * Small text below the number.
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Hex color for the stat numbers (e.g. #facc15 for yellow).
             */
            statsColor?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'worldMap';
          }
        | {
            heading: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            /**
             * Hex color for the circle behind the image (e.g. #facc15 for yellow).
             */
            circleColor?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV3';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            /**
             * Hex color for the circle behind the image (e.g. #facc15 for yellow).
             */
            circleColor?: string | null;
            /**
             * Logos displayed in a grid below the heading and content.
             */
            logos?:
              | {
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  alt: string;
                  /**
                   * Show the logo in its original colors instead of grayscale/inverted.
                   */
                  disableFilter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV4';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel: string;
            /**
             * Use mailto: for email links or a URL.
             */
            buttonHref: string;
            /**
             * Hex color for the button background (e.g. #facc15 for yellow).
             */
            buttonColor?: string | null;
            linkedinUrl?: string | null;
            githubUrl?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            description?: string | null;
            projects?:
              | {
                  title: string;
                  description?: string | null;
                  stats?:
                    | {
                        /**
                         * e.g. "Revenue", "Users", "Performance"
                         */
                        label?: string | null;
                        /**
                         * e.g. "+25%", "10K", "99.9%"
                         */
                        value: string;
                        trend?: ('up' | 'neutral' | 'down') | null;
                        id?: string | null;
                      }[]
                    | null;
                  buttonLabel?: string | null;
                  /**
                   * URL the button links to.
                   */
                  buttonHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            heading?: string | null;
            description?: string | null;
            /**
             * Number of cards per row on desktop.
             */
            columns?: ('2' | '3' | '4') | null;
            cards?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional URL the card links to.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Text for the button below the cards. Only shows when cards exceed 2 rows.
             */
            buttonLabel?: string | null;
            /**
             * URL the button links to.
             */
            buttonHref?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsV2';
          }
        | {
            heading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutSimple';
          }
        | {
            images?:
              | {
                  image?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Duration in seconds for one full scroll cycle. Lower = faster.
             */
            speed?: number | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSlider';
          }
        | {
            heading: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV5';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            /**
             * Logos displayed in a grid below the heading and content.
             */
            logos?:
              | {
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  alt: string;
                  /**
                   * Show the logo in its original colors instead of grayscale/inverted.
                   */
                  disableFilter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV6';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            description?: string | null;
            events?:
              | {
                  date: string;
                  title: string;
                  description?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            description?: string | null;
            tiers?:
              | {
                  name: string;
                  price: string;
                  period?: string | null;
                  description?: string | null;
                  highlighted?: boolean | null;
                  buttonLabel?: string | null;
                  buttonHref?: string | null;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  title: string;
                  description: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            heading?: string | null;
            description?: string | null;
            columns?: ('1' | '2' | '3') | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureList';
          }
        | {
            text: string;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            variant?: ('default' | 'accent' | 'subtle') | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            heading?: string | null;
            description?: string | null;
            email?: string | null;
            phone?: string | null;
            location?: string | null;
            linkedinUrl?: string | null;
            githubUrl?: string | null;
            twitterUrl?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            heading?: string | null;
            columns?:
              | {
                  title?: string | null;
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentColumns';
          }
        | {
            quote: string;
            author?: string | null;
            role?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blockquote';
          }
        | {
            heading?: string | null;
            description?: string | null;
            cards?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  size?: ('normal' | 'wide') | null;
                  /**
                   * Optional hex color for card accent (e.g. #facc15)
                   */
                  accentColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bentoGrid';
          }
        | {
            heading?: string | null;
            speed?: ('slow' | 'normal' | 'fast') | null;
            logos?:
              | {
                  logo?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  name: string;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoMarquee';
          }
        | {
            heading?: string | null;
            tabs?:
              | {
                  label: string;
                  icon?: string | null;
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabsContent';
          }
        | {
            heading: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: {
              source?: ('upload' | 'url') | null;
              upload?: (number | null) | Media;
              /**
               * Full URL to an image (JPG, PNG, WebP, SVG)
               */
              url?: string | null;
            };
            layout?: ('imageRight' | 'imageLeft') | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitSection';
          }
        | {
            heading?: string | null;
            description?: string | null;
            columns?: ('1' | '2') | null;
            items?:
              | {
                  text: string;
                  /**
                   * Uncheck to show as excluded (with X icon)
                   */
                  included?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            heading?: string | null;
            description?: string | null;
            columns?: ('2' | '3' | '4') | null;
            cards?:
              | {
                  image?: {
                    source?: ('upload' | 'url') | null;
                    upload?: (number | null) | Media;
                    /**
                     * Full URL to an image (JPG, PNG, WebP, SVG)
                     */
                    url?: string | null;
                  };
                  title: string;
                  description?: string | null;
                  tag?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            heading?: string | null;
            description?: string | null;
            /**
             * YouTube or Vimeo URL (e.g. https://www.youtube.com/watch?v=...)
             */
            videoUrl: string;
            layout?: ('centered' | 'split') | null;
            aspectRatio?: ('16/9' | '4/3' | '1/1') | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoSection';
          }
        | {
            /**
             * Text that scrolls continuously. Will be repeated.
             */
            text: string;
            /**
             * Character between repeated text (e.g. •, /, |, ★)
             */
            separator?: string | null;
            speed?: ('slow' | 'normal' | 'fast') | null;
            size?: ('sm' | 'md' | 'lg' | 'xl') | null;
            variant?: ('default' | 'outline' | 'muted') | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textMarquee';
          }
        | {
            heading?: string | null;
            description?: string | null;
            columns?: ('3' | '4' | '5' | '6') | null;
            items?:
              | {
                  icon?: string | null;
                  label: string;
                  sublabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'iconGrid';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  /**
                   * The number to count up to (e.g. 150, 400, 25)
                   */
                  value: number;
                  /**
                   * Text after the number (e.g. +, %, M, K)
                   */
                  suffix?: string | null;
                  /**
                   * Text before the number (e.g. $, €)
                   */
                  prefix?: string | null;
                  label: string;
                  /**
                   * Optional hex color for the number (e.g. #facc15)
                   */
                  accentColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            spacingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberCounter';
          }
      )[]
    | null;
  meta?: {
    /**
     * Overrides the default site title.
     */
    title?: string | null;
    /**
     * Overrides the default site description.
     */
    description?: string | null;
    ogImage?: {
      source?: ('upload' | 'url') | null;
      upload?: (number | null) | Media;
      /**
       * Full URL to an image (JPG, PNG, WebP, SVG)
       */
      url?: string | null;
    };
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create forms and use #form:slug in any button link to open them as a popup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * Internal name — not shown to visitors.
   */
  title: string;
  /**
   * Use this in button links as #form:your-slug to open this form as a popup.
   */
  slug: string;
  /**
   * Optional heading shown at the top of the popup.
   */
  heading?: string | null;
  /**
   * Optional description below the heading.
   */
  popupDescription?: string | null;
  /**
   * Email shown to the user after successful submission.
   */
  recipientEmail: string;
  /**
   * Message shown after successful submission.
   */
  successMessage?: string | null;
  submitLabel?: string | null;
  /**
   * Hex color (e.g. #facc15).
   */
  buttonColor?: string | null;
  /**
   * Add fields to the form. Email field is required for submissions.
   */
  fields?:
    | {
        /**
         * Internal name (e.g. email, name, message). Must be unique within the form.
         */
        name: string;
        /**
         * Optional label shown above the field. If empty, no label is rendered.
         */
        label?: string | null;
        type: 'text' | 'email' | 'textarea' | 'tel' | 'url' | 'number';
        /**
         * Faded hint text shown when the field is empty.
         */
        placeholder?: string | null;
        required?: boolean | null;
        width?: ('full' | 'half') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form?: (number | null) | Form;
  email: string;
  message?: string | null;
  /**
   * Raw JSON of all submitted field values.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: string | null;
  ip?: string | null;
  blocked?: boolean | null;
  blockReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  optimizeFormat?: T;
  optimizeQuality?: T;
  optimizeMaxWidth?: T;
  optimizeMaxHeight?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              mainText?: T;
              readMoreLabel?: T;
              readMoreHref?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              overlayPart1?: T;
              overlayPart2?: T;
              circleColor?: T;
              locationText?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        companies?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    name?: T;
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              speed?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              description?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    featured?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        aboutMe?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    title?: T;
                    text?: T;
                    image?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        heroV2?:
          | T
          | {
              logos?:
                | T
                | {
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    alt?: T;
                    disableFilter?: T;
                    id?: T;
                  };
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              overlayPart1?: T;
              overlayPart2?: T;
              circleColor?: T;
              locationText?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        worldMap?:
          | T
          | {
              heading?: T;
              description?: T;
              lineColor?: T;
              dotColor?: T;
              showLabels?: T;
              loop?: T;
              connections?:
                | T
                | {
                    startCity?: T;
                    endCity?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              statsColor?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        heroV3?:
          | T
          | {
              heading?: T;
              content?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              circleColor?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        heroV4?:
          | T
          | {
              heading?: T;
              content?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              circleColor?: T;
              logos?:
                | T
                | {
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    alt?: T;
                    disableFilter?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonHref?: T;
              buttonColor?: T;
              linkedinUrl?: T;
              githubUrl?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              heading?: T;
              description?: T;
              projects?:
                | T
                | {
                    title?: T;
                    description?: T;
                    stats?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          trend?: T;
                          id?: T;
                        };
                    buttonLabel?: T;
                    buttonHref?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        projectsV2?:
          | T
          | {
              heading?: T;
              description?: T;
              columns?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              buttonLabel?: T;
              buttonHref?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        aboutSimple?:
          | T
          | {
              heading?: T;
              description?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        imageSlider?:
          | T
          | {
              images?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    alt?: T;
                    id?: T;
                  };
              speed?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        heroV5?:
          | T
          | {
              heading?: T;
              content?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        heroV6?:
          | T
          | {
              heading?: T;
              content?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              logos?:
                | T
                | {
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    alt?: T;
                    disableFilter?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              description?: T;
              events?:
                | T
                | {
                    date?: T;
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              heading?: T;
              description?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    period?: T;
                    description?: T;
                    highlighted?: T;
                    buttonLabel?: T;
                    buttonHref?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              heading?: T;
              description?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              variant?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              heading?: T;
              description?: T;
              email?: T;
              phone?: T;
              location?: T;
              linkedinUrl?: T;
              githubUrl?: T;
              twitterUrl?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        contentColumns?:
          | T
          | {
              heading?: T;
              columns?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        blockquote?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        bentoGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    size?: T;
                    accentColor?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        logoMarquee?:
          | T
          | {
              heading?: T;
              speed?: T;
              logos?:
                | T
                | {
                    logo?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    name?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        tabsContent?:
          | T
          | {
              heading?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    content?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        splitSection?:
          | T
          | {
              heading?: T;
              description?: T;
              image?:
                | T
                | {
                    source?: T;
                    upload?: T;
                    url?: T;
                  };
              layout?: T;
              buttonLabel?: T;
              buttonHref?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              heading?: T;
              description?: T;
              columns?: T;
              items?:
                | T
                | {
                    text?: T;
                    included?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              columns?: T;
              cards?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          upload?: T;
                          url?: T;
                        };
                    title?: T;
                    description?: T;
                    tag?: T;
                    href?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        videoSection?:
          | T
          | {
              heading?: T;
              description?: T;
              videoUrl?: T;
              layout?: T;
              aspectRatio?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        textMarquee?:
          | T
          | {
              text?: T;
              separator?: T;
              speed?: T;
              size?: T;
              variant?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        iconGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    sublabel?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        numberCounter?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    prefix?: T;
                    label?: T;
                    accentColor?: T;
                    id?: T;
                  };
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?:
          | T
          | {
              source?: T;
              upload?: T;
              url?: T;
            };
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heading?: T;
  popupDescription?: T;
  recipientEmail?: T;
  successMessage?: T;
  submitLabel?: T;
  buttonColor?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        placeholder?: T;
        required?: T;
        width?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  email?: T;
  message?: T;
  data?: T;
  source?: T;
  ip?: T;
  blocked?: T;
  blockReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used as fallback in <title> tags.
   */
  siteName?: string | null;
  /**
   * Used when a page has no individual meta description.
   */
  siteDescription?: string | null;
  defaultOgImage?: {
    source?: ('upload' | 'url') | null;
    upload?: (number | null) | Media;
    /**
     * Full URL to an image (JPG, PNG, WebP, SVG)
     */
    url?: string | null;
  };
  /**
   * URL to a .ico, .png, or .svg favicon.
   */
  faviconUrl?: string | null;
  /**
   * e.g. G-XXXXXXXXXX
   */
  googleAnalyticsId?: string | null;
  /**
   * Hex color code used as the brand primary color.
   */
  primaryColor?: string | null;
  twitterHandle?: string | null;
  headingFontSource?: ('google' | 'custom') | null;
  /**
   * Exact Google Fonts name, e.g. "Inter", "Playfair Display", "Space Grotesk".
   */
  headingFontGoogle?: string | null;
  /**
   * Upload a .woff2 font file for headings.
   */
  headingFontFile?: (number | null) | Media;
  /**
   * CSS font-weight value, e.g. "700", "400..900" for variable fonts.
   */
  headingFontWeight?: string | null;
  bodyFontSource?: ('google' | 'custom') | null;
  /**
   * Exact Google Fonts name, e.g. "Inter", "DM Sans", "Outfit".
   */
  bodyFontGoogle?: string | null;
  /**
   * Upload a .woff2 font file for body text.
   */
  bodyFontFile?: (number | null) | Media;
  /**
   * CSS font-weight value, e.g. "400", "100..900" for variable fonts.
   */
  bodyFontWeight?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Paste a URL to your logo image (PNG, SVG, WebP). Leave blank to use the default icon.
   */
  logoUrl?: string | null;
  logoAlt?: string | null;
  /**
   * Height of the logo in pixels (16–80px). Width scales automatically.
   */
  logoHeight?: number | null;
  navItems?:
    | {
        label: string;
        href: string;
        dropdownItems?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logoText?: string | null;
  description?: string | null;
  /**
   * Leave blank to auto-generate with current year.
   */
  copyrightText?: string | null;
  githubUrl?: string | null;
  linkedinUrl?: string | null;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  youtubeUrl?: string | null;
  /**
   * Leave empty to use default links.
   */
  linkGroups?:
    | {
        label: string;
        links?:
          | {
              title: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultOgImage?:
    | T
    | {
        source?: T;
        upload?: T;
        url?: T;
      };
  faviconUrl?: T;
  googleAnalyticsId?: T;
  primaryColor?: T;
  twitterHandle?: T;
  headingFontSource?: T;
  headingFontGoogle?: T;
  headingFontFile?: T;
  headingFontWeight?: T;
  bodyFontSource?: T;
  bodyFontGoogle?: T;
  bodyFontFile?: T;
  bodyFontWeight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoUrl?: T;
  logoAlt?: T;
  logoHeight?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoText?: T;
  description?: T;
  copyrightText?: T;
  githubUrl?: T;
  linkedinUrl?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  youtubeUrl?: T;
  linkGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              title?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}