export interface CityCoord {
  lat: number
  lng: number
  label: string
}

export const cityCoordinates: Record<string, CityCoord> = {
  // ── European Capitals ──
  'tirana': { lat: 41.3275, lng: 19.8187, label: 'Tirana' },
  'andorra-la-vella': { lat: 42.5063, lng: 1.5218, label: 'Andorra la Vella' },
  'vienna': { lat: 48.2082, lng: 16.3738, label: 'Vienna' },
  'minsk': { lat: 53.9006, lng: 27.559, label: 'Minsk' },
  'brussels': { lat: 50.8503, lng: 4.3517, label: 'Brussels' },
  'sarajevo': { lat: 43.8563, lng: 18.4131, label: 'Sarajevo' },
  'sofia': { lat: 42.6977, lng: 23.3219, label: 'Sofia' },
  'zagreb': { lat: 45.815, lng: 15.9819, label: 'Zagreb' },
  'nicosia': { lat: 35.1856, lng: 33.3823, label: 'Nicosia' },
  'prague': { lat: 50.0755, lng: 14.4378, label: 'Prague' },
  'copenhagen': { lat: 55.6761, lng: 12.5683, label: 'Copenhagen' },
  'tallinn': { lat: 59.437, lng: 24.7536, label: 'Tallinn' },
  'helsinki': { lat: 60.1699, lng: 24.9384, label: 'Helsinki' },
  'paris': { lat: 48.8566, lng: 2.3522, label: 'Paris' },
  'berlin': { lat: 52.52, lng: 13.405, label: 'Berlin' },
  'athens': { lat: 37.9838, lng: 23.7275, label: 'Athens' },
  'budapest': { lat: 47.4979, lng: 19.0402, label: 'Budapest' },
  'reykjavik': { lat: 64.1466, lng: -21.9426, label: 'Reykjavik' },
  'dublin': { lat: 53.3498, lng: -6.2603, label: 'Dublin' },
  'rome': { lat: 41.9028, lng: 12.4964, label: 'Rome' },
  'pristina': { lat: 42.6629, lng: 21.1655, label: 'Pristina' },
  'riga': { lat: 56.9496, lng: 24.1052, label: 'Riga' },
  'vaduz': { lat: 47.141, lng: 9.5215, label: 'Vaduz' },
  'vilnius': { lat: 54.6872, lng: 25.2797, label: 'Vilnius' },
  'luxembourg': { lat: 49.6117, lng: 6.1319, label: 'Luxembourg' },
  'skopje': { lat: 41.9973, lng: 21.428, label: 'Skopje' },
  'valletta': { lat: 35.8989, lng: 14.5146, label: 'Valletta' },
  'chisinau': { lat: 47.0105, lng: 28.8638, label: 'Chisinau' },
  'monaco': { lat: 43.7384, lng: 7.4246, label: 'Monaco' },
  'podgorica': { lat: 42.4304, lng: 19.2594, label: 'Podgorica' },
  'amsterdam': { lat: 52.3676, lng: 4.9041, label: 'Amsterdam' },
  'oslo': { lat: 59.9139, lng: 10.7522, label: 'Oslo' },
  'warsaw': { lat: 52.2297, lng: 21.0122, label: 'Warsaw' },
  'lisbon': { lat: 38.7223, lng: -9.1393, label: 'Lisbon' },
  'bucharest': { lat: 44.4268, lng: 26.1025, label: 'Bucharest' },
  'moscow': { lat: 55.7558, lng: 37.6173, label: 'Moscow' },
  'belgrade': { lat: 44.7866, lng: 20.4489, label: 'Belgrade' },
  'bratislava': { lat: 48.1486, lng: 17.1077, label: 'Bratislava' },
  'ljubljana': { lat: 46.0569, lng: 14.5058, label: 'Ljubljana' },
  'madrid': { lat: 40.4168, lng: -3.7038, label: 'Madrid' },
  'stockholm': { lat: 59.3293, lng: 18.0686, label: 'Stockholm' },
  'bern': { lat: 46.948, lng: 7.4474, label: 'Bern' },
  'kyiv': { lat: 50.4501, lng: 30.5234, label: 'Kyiv' },
  'london': { lat: 51.5074, lng: -0.1278, label: 'London' },

  // ── US State Capitals ──
  'montgomery': { lat: 32.3792, lng: -86.3077, label: 'Montgomery, AL' },
  'juneau': { lat: 58.3005, lng: -134.4197, label: 'Juneau, AK' },
  'phoenix': { lat: 33.4484, lng: -112.074, label: 'Phoenix, AZ' },
  'little-rock': { lat: 34.7465, lng: -92.2896, label: 'Little Rock, AR' },
  'sacramento': { lat: 38.5816, lng: -121.4944, label: 'Sacramento, CA' },
  'denver': { lat: 39.7392, lng: -104.9903, label: 'Denver, CO' },
  'hartford': { lat: 41.7658, lng: -72.6734, label: 'Hartford, CT' },
  'dover': { lat: 39.1582, lng: -75.5244, label: 'Dover, DE' },
  'tallahassee': { lat: 30.4383, lng: -84.2807, label: 'Tallahassee, FL' },
  'atlanta': { lat: 33.749, lng: -84.388, label: 'Atlanta, GA' },
  'honolulu': { lat: 21.3069, lng: -157.8583, label: 'Honolulu, HI' },
  'boise': { lat: 43.615, lng: -116.2023, label: 'Boise, ID' },
  'springfield-il': { lat: 39.7817, lng: -89.6501, label: 'Springfield, IL' },
  'indianapolis': { lat: 39.7684, lng: -86.1581, label: 'Indianapolis, IN' },
  'des-moines': { lat: 41.5868, lng: -93.625, label: 'Des Moines, IA' },
  'topeka': { lat: 39.0473, lng: -95.6752, label: 'Topeka, KS' },
  'frankfort': { lat: 38.2009, lng: -84.8733, label: 'Frankfort, KY' },
  'baton-rouge': { lat: 30.4515, lng: -91.1871, label: 'Baton Rouge, LA' },
  'augusta': { lat: 44.3106, lng: -69.7795, label: 'Augusta, ME' },
  'annapolis': { lat: 38.9784, lng: -76.4922, label: 'Annapolis, MD' },
  'boston': { lat: 42.3601, lng: -71.0589, label: 'Boston, MA' },
  'lansing': { lat: 42.7325, lng: -84.5555, label: 'Lansing, MI' },
  'saint-paul': { lat: 44.9537, lng: -93.09, label: 'Saint Paul, MN' },
  'jackson': { lat: 32.2988, lng: -90.1848, label: 'Jackson, MS' },
  'jefferson-city': { lat: 38.5768, lng: -92.1735, label: 'Jefferson City, MO' },
  'helena': { lat: 46.5884, lng: -112.0245, label: 'Helena, MT' },
  'lincoln': { lat: 40.8136, lng: -96.7026, label: 'Lincoln, NE' },
  'carson-city': { lat: 39.1638, lng: -119.7674, label: 'Carson City, NV' },
  'concord': { lat: 43.2081, lng: -71.5376, label: 'Concord, NH' },
  'trenton': { lat: 40.2171, lng: -74.7429, label: 'Trenton, NJ' },
  'santa-fe': { lat: 35.687, lng: -105.9378, label: 'Santa Fe, NM' },
  'albany': { lat: 42.6526, lng: -73.7562, label: 'Albany, NY' },
  'raleigh': { lat: 35.7796, lng: -78.6382, label: 'Raleigh, NC' },
  'bismarck': { lat: 46.8083, lng: -100.7837, label: 'Bismarck, ND' },
  'columbus': { lat: 39.9612, lng: -82.9988, label: 'Columbus, OH' },
  'oklahoma-city': { lat: 35.4676, lng: -97.5164, label: 'Oklahoma City, OK' },
  'salem': { lat: 44.9429, lng: -123.0351, label: 'Salem, OR' },
  'harrisburg': { lat: 40.2732, lng: -76.8867, label: 'Harrisburg, PA' },
  'providence': { lat: 41.824, lng: -71.4128, label: 'Providence, RI' },
  'columbia': { lat: 34.0007, lng: -81.0348, label: 'Columbia, SC' },
  'pierre': { lat: 44.3683, lng: -100.351, label: 'Pierre, SD' },
  'nashville': { lat: 36.1627, lng: -86.7816, label: 'Nashville, TN' },
  'austin': { lat: 30.2672, lng: -97.7431, label: 'Austin, TX' },
  'salt-lake-city': { lat: 40.7608, lng: -111.891, label: 'Salt Lake City, UT' },
  'montpelier': { lat: 44.2601, lng: -72.5754, label: 'Montpelier, VT' },
  'richmond': { lat: 37.5407, lng: -77.436, label: 'Richmond, VA' },
  'olympia': { lat: 47.0379, lng: -122.9007, label: 'Olympia, WA' },
  'charleston': { lat: 38.3498, lng: -81.6326, label: 'Charleston, WV' },
  'madison': { lat: 43.0731, lng: -89.4012, label: 'Madison, WI' },
  'cheyenne': { lat: 41.14, lng: -104.8202, label: 'Cheyenne, WY' },
  'washington-dc': { lat: 38.9072, lng: -77.0369, label: 'Washington, D.C.' },

  // ── Regions ──
  'emea': { lat: 48.0, lng: 20.0, label: 'EMEA' },
  'usa': { lat: 39.8283, lng: -98.5795, label: 'USA' },
  'canada': { lat: 56.1304, lng: -106.3468, label: 'Canada' },
  'australia': { lat: -25.2744, lng: 133.7751, label: 'Australia' },
  'new-zealand': { lat: -40.9006, lng: 174.886, label: 'New Zealand' },
}

/** Sorted options for Payload select fields, grouped */
export const cityOptions: { label: string; value: string }[] = [
  // European Capitals
  { label: '── Europe ──', value: '_europe_header' },
  { label: 'Amsterdam', value: 'amsterdam' },
  { label: 'Andorra la Vella', value: 'andorra-la-vella' },
  { label: 'Athens', value: 'athens' },
  { label: 'Belgrade', value: 'belgrade' },
  { label: 'Berlin', value: 'berlin' },
  { label: 'Bern', value: 'bern' },
  { label: 'Bratislava', value: 'bratislava' },
  { label: 'Brussels', value: 'brussels' },
  { label: 'Bucharest', value: 'bucharest' },
  { label: 'Budapest', value: 'budapest' },
  { label: 'Chisinau', value: 'chisinau' },
  { label: 'Copenhagen', value: 'copenhagen' },
  { label: 'Dublin', value: 'dublin' },
  { label: 'Helsinki', value: 'helsinki' },
  { label: 'Kyiv', value: 'kyiv' },
  { label: 'Ljubljana', value: 'ljubljana' },
  { label: 'London', value: 'london' },
  { label: 'Luxembourg', value: 'luxembourg' },
  { label: 'Madrid', value: 'madrid' },
  { label: 'Minsk', value: 'minsk' },
  { label: 'Monaco', value: 'monaco' },
  { label: 'Moscow', value: 'moscow' },
  { label: 'Nicosia', value: 'nicosia' },
  { label: 'Oslo', value: 'oslo' },
  { label: 'Paris', value: 'paris' },
  { label: 'Podgorica', value: 'podgorica' },
  { label: 'Prague', value: 'prague' },
  { label: 'Pristina', value: 'pristina' },
  { label: 'Reykjavik', value: 'reykjavik' },
  { label: 'Riga', value: 'riga' },
  { label: 'Rome', value: 'rome' },
  { label: 'Sarajevo', value: 'sarajevo' },
  { label: 'Skopje', value: 'skopje' },
  { label: 'Sofia', value: 'sofia' },
  { label: 'Stockholm', value: 'stockholm' },
  { label: 'Tallinn', value: 'tallinn' },
  { label: 'Tirana', value: 'tirana' },
  { label: 'Vaduz', value: 'vaduz' },
  { label: 'Valletta', value: 'valletta' },
  { label: 'Vienna', value: 'vienna' },
  { label: 'Vilnius', value: 'vilnius' },
  { label: 'Warsaw', value: 'warsaw' },
  { label: 'Zagreb', value: 'zagreb' },
  // US State Capitals
  { label: '── USA ──', value: '_usa_header' },
  { label: 'Albany, NY', value: 'albany' },
  { label: 'Annapolis, MD', value: 'annapolis' },
  { label: 'Atlanta, GA', value: 'atlanta' },
  { label: 'Augusta, ME', value: 'augusta' },
  { label: 'Austin, TX', value: 'austin' },
  { label: 'Baton Rouge, LA', value: 'baton-rouge' },
  { label: 'Bismarck, ND', value: 'bismarck' },
  { label: 'Boise, ID', value: 'boise' },
  { label: 'Boston, MA', value: 'boston' },
  { label: 'Carson City, NV', value: 'carson-city' },
  { label: 'Charleston, WV', value: 'charleston' },
  { label: 'Cheyenne, WY', value: 'cheyenne' },
  { label: 'Columbia, SC', value: 'columbia' },
  { label: 'Columbus, OH', value: 'columbus' },
  { label: 'Concord, NH', value: 'concord' },
  { label: 'Denver, CO', value: 'denver' },
  { label: 'Des Moines, IA', value: 'des-moines' },
  { label: 'Dover, DE', value: 'dover' },
  { label: 'Frankfort, KY', value: 'frankfort' },
  { label: 'Harrisburg, PA', value: 'harrisburg' },
  { label: 'Hartford, CT', value: 'hartford' },
  { label: 'Helena, MT', value: 'helena' },
  { label: 'Honolulu, HI', value: 'honolulu' },
  { label: 'Indianapolis, IN', value: 'indianapolis' },
  { label: 'Jackson, MS', value: 'jackson' },
  { label: 'Jefferson City, MO', value: 'jefferson-city' },
  { label: 'Juneau, AK', value: 'juneau' },
  { label: 'Lansing, MI', value: 'lansing' },
  { label: 'Lincoln, NE', value: 'lincoln' },
  { label: 'Little Rock, AR', value: 'little-rock' },
  { label: 'Madison, WI', value: 'madison' },
  { label: 'Montgomery, AL', value: 'montgomery' },
  { label: 'Montpelier, VT', value: 'montpelier' },
  { label: 'Nashville, TN', value: 'nashville' },
  { label: 'Oklahoma City, OK', value: 'oklahoma-city' },
  { label: 'Olympia, WA', value: 'olympia' },
  { label: 'Phoenix, AZ', value: 'phoenix' },
  { label: 'Pierre, SD', value: 'pierre' },
  { label: 'Providence, RI', value: 'providence' },
  { label: 'Raleigh, NC', value: 'raleigh' },
  { label: 'Richmond, VA', value: 'richmond' },
  { label: 'Sacramento, CA', value: 'sacramento' },
  { label: 'Saint Paul, MN', value: 'saint-paul' },
  { label: 'Salem, OR', value: 'salem' },
  { label: 'Salt Lake City, UT', value: 'salt-lake-city' },
  { label: 'Santa Fe, NM', value: 'santa-fe' },
  { label: 'Springfield, IL', value: 'springfield-il' },
  { label: 'Tallahassee, FL', value: 'tallahassee' },
  { label: 'Topeka, KS', value: 'topeka' },
  { label: 'Trenton, NJ', value: 'trenton' },
  { label: 'Washington, D.C.', value: 'washington-dc' },
  // Regions
  { label: '── Regions ──', value: '_regions_header' },
  { label: 'EMEA', value: 'emea' },
  { label: 'USA', value: 'usa' },
  { label: 'Canada', value: 'canada' },
  { label: 'Australia', value: 'australia' },
  { label: 'New Zealand', value: 'new-zealand' },
]
